

gd_artnews_time <- function(ARTNEWS_TIME_FILE = PMDATA_LOCS$ARTNEWS_TIME_FILE) {
    if (as.character(match.call()[[1]]) %in% fstd){browser()}
    1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;
    

    dt_artnews_time <- fread(ARTNEWS_TIME_FILE)

    ## check whether location is handled properly: yea seems to be unique within collector
    dt_artnews_time[, .N, clctr_name]
    dt_artnews_time[, .N, .(clctr_name, location)]
    dt_artnews_time[grepl("David Bowie", clctr_name)]

    ## look at couples, "and" seems to be pretty good differentiator
    dt_artnews_time[grepl("and", clctr_name), .N, clctr_name] %>% print(n=300)

    
}

PMDATA_LOCS <- gc_pmdata_locs()
gd_artnews_time()


#' generate the artnews collector file
#' here manually it has to be checked manually whether a collector entry in artnews ranking refers to single person
#' @param ARTNEWS_TIME_FILE the year-ranking-collector file
#' @param ARTNEWS_COLLECTOR_ENTRIES_FILE the output that gets produced: unique collectors, with ID (Artnews-collector-entity, ACE) and heuristic of whether they are a couple
gwd_artnews_clctr <- function(ARTNEWS_TIME_FILE = PMDATA_LOCS$ARTNEWS_TIME_FILE,
                              ARTNEWS_COLLECTOR_ENTRIES_FILE = PMDATA_LOCS$ARTNEWS_COLLECTOR_ENTRIES_FILE) {

    dt_artnews_time <- fread(ARTNEWS_TIME_FILE)

    ## heuristic coding ("and" present)  whether collector refers to couple
    dt_artnews_time[, .(clctr_name = funique(clctr_name))] %>%
        .[, .(an_entry_id = paste0("ACE", 1:.N), clctr_name,
              is_couple = fifelse(grepl(" and ", clctr_name), 1, 0))] %>%        
        fwrite(paste0(ARTNEWS_COLLECTOR_ENTRIES_FILE))

}

## ONLY RUN ONCE:
## the ARTNEWS_COLLECTOR_ENTRIES_FILE has to be checked manually whether the heuristic coding is correct
## gwd_artnews_clctr()

#' reads ARTNEWS_COLLECTOR_ENTRIES_FILE, duplicates couple rows to make reduction to person simpler
#'
#' e.g. entry "John Doe and Jane Smith" is repeated twice in ARTNEWS_COLLECTOR_PERSON_FILE (since in previous step in gwd_artnews_clctr) identified as couple, and is now replaced manually by two entries, "John Doe" and "Jane Smith" (deleting takes less keystrokes than expanding)
#' manual checking takes place in org-mode due to better table-editing capabilities (edits don't yeet indentation, which is the case in csv-mode). `an_clctr_person.org` is manually generated from ARTNEWS_COLLECTOR_ENTRIES_FILE via macros/replace-string, and then exported to via `org-table-export` to .csv (ARTNEWS_COLLECTOR_PERSON_FILE_ORG)
#' @param ARTNEWS_COLLECTOR_ENTRIES_FILE file generated by gwd_artnews_clctr, !!!AFTER BEING MANUALLY CHECKED THAT ALL COLLECTOR ENTRIES INDICATED TO BE COUPLES ARE IN FACT COUPLES!!!
#' @param ARTNEWS_COLLECTOR_PERSON_FILE ARTNEWS_COLLECTOR_ENTRIES_FILE, but with duplicated couple rows so that reduction to persons is easier. also has a person ID (Artnews person entity, "APE"; with indexing for couples, .e.g "APE10b" for second person in collector couple that is ACE10
gwd_artnews_person <- function(ARTNEWS_COLLECTOR_ENTRIES_FILE = PMDATA_LOCS$ARTNEWS_COLLECTOR_ENTRIES_FILE,
                               ARTNEWS_COLLECTOR_PERSON_FILE = PMDATA_LOCS$ARTNEWS_COLLECTOR_PERSON_FILE) {
    if (as.character(match.call()[[1]]) %in% fstd){browser()}
    1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;

    
    dt_an_clctr_entries <- fread(ARTNEWS_COLLECTOR_ENTRIES_FILE)
    
    ## already copy the couple lines, saves manually copying (just have to delete the wrong parts)
    dt_an_person_prep <- rbind(dt_an_clctr_entries, dt_an_clctr_entries[is_couple==1]) %>% 
        .[, ace_nbr := as.integer(substring(an_entry_id, 4, nchar(an_entry_id)))] %>%
        .[, an_person_id := paste0("APE", ace_nbr, letters[1:.N]), an_entry_id] %>%
        .[order(-is_couple, ace_nbr)] %>%
        .[, .(an_entry_id, an_person_id, clctr_name, is_couple)]

        
    fwrite(dt_an_person_prep, ARTNEWS_COLLECTOR_PERSON_FILE)
    ## dt_an_person_prep
}
        
                             
        
## ONLY RUN ONCE:
## this duplicates couple rows so that manual deletion is easier
## names are not standardized for automatic detection of both names
## gwd_artnews_person()
dtx <- fread(PMDATA_LOCS$ARTNEWS_COLLECTOR_PERSON_FILE_ORG)
