## * MOW import


#' generate data.table of MOW entries
#' @param dt_pmdb data.table of private museums, generated by gd_pmdb
#' @param dt_mow_info data.table of MOW entries, generated by gd_mow_info
test_mow_pmdb_cvrg <- function(dt_pmdb, dt_mow_info) {
    
    tinytest::expect_true(T)
}

## test_mow_pmdb_cvrg(1,2)
## tinytest::expect_true(T)


#' read the file of results after manually checking PMDB entries for corresponding matches in MOW
#' one row per PM
#' @param MOW_PMDB_MATCHRES_FILE the location of the match results file
#' @return data.table with 2 columns: PMDB_ID and MOW_ID where match exist, "nomatch" if no match exists
gd_mow_pmdb_matchres <- function(MOW_PMDB_MATCHRES_FILE = PMDATA_LOCS$MOW_PMDB_MATCHRES_FILE) {
    ## look at how many stuff is already checked
    if (file.exists(MOW_PMDB_MATCHRES_FILE)) {
        dt_res <- fread(MOW_PMDB_MATCHRES_FILE)
    } else {
        dt_res <- data.table(PMDB_ID=character(), MOW_ID = character())
    }

    return(dt_res)
}

#' generate the MOW info file: one line per MOW entry
#' has matches with PMDB (column PMDB_ID) where available
#' @param MOW_INFO_FILE csv file produced by mow.py with one mow entry per line
#' @param MOW_PMDB_MATCHRES_FILE two-column csv file with links from PMDB IDs to MOW IDs, where available
#' @return data.table of MOW_INFO_FILE with data.table of MOW_PMDB_MATCHRES_FILE joined to it
#' @export
gd_mow_info <- function(MOW_INFO_FILE = PMDATA_LOCS$MOW_INFO_FILE,
                        MOW_PMDB_MATCHRES_FILE = PMDATA_LOCS$MOW_PMDB_MATCHRES_FILE) {
    
    ## if (as.character(match.call()[[1]]) %in% fstd){browser()}
    ## 1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;
    iso3c <- country <- MOW_ID <- PMDB_ID <- idx <- NULL
    

    dt_mow_info <- fread(MOW_INFO_FILE) %>%
        .[, iso3c := countrycode(country, "country.name", "iso3c")]
    
    
    ## read in the matches to PMDB
    dt_mow_pmdb_match <- fread(MOW_PMDB_MATCHRES_FILE)

    if (dt_mow_pmdb_match[MOW_ID != "nomatch", any_duplicated(MOW_ID)]) {stop("some MOW_IDs are duplicated")}
    if (dt_mow_pmdb_match[, any_duplicated(PMDB_ID)]) {stop("some PMDB_IDs are duplicated")}

    ## match 
    dt_mow_info2 <- dt_mow_pmdb_match[dt_mow_info, on = .(MOW_ID = idx)] %>%
        setcolorder(.c(MOW_ID, PMDB_ID))
    

    ## hmm there are a bunch whose opening date is stuff like 20th century, which gets parsed as 20
    ## dt_mow_info[founding_date1 < 100, .(name, founding_date1)] %>% print(n=300)

    ## dt_mow_info[founding_date1 < 1700, .(name, founding_date1)] %>% print(n=300)

    ## less than 1% (366) are before 1800, only 71 before 1500
    ## attr(dt_mow_info2, "gnrtdby") <- as.character(match.call()[[1]])
    return(dt_mow_info2)

    ## dt_mow_info[, .N, .(iso3c, founding_date1)] %>% na.omit %>%
    ##     .[, Nsum := sum(N), iso3c] %>%
    ##     .[, Nprop := N/Nsum] %>% 
    ##     .[Nsum > 500] %>% 
    ##     ggplot(aes(x=founding_date1, y=Nprop, group = iso3c)) + geom_line() +
    ##     xlim(1900,max(dt_mow_info$founding_date1, na.rm = T))
    
}

## gd_mow_info(gc_pmdata_locs()$MOW_INFO_FILE, gc_pmdata_locs()$MOW_PMDB_MATCHRES_FILE)


gd_mow_tags <- function() {
}
    

    
